version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_PATH=/app/database/cotacoes.db
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./database:/data
