name: Testing

on:
  push:
    branches: ["main"]
    paths:
      - "**.go"
  pull_request:
    branches: ["main"]
    paths:
      - "**.go"

jobs:
  build-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up GO
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./..
    
    - name: Testing
      run: go test -v ./..